#!/bin/bash
# scripts/kernel_hardening.sh
# ================================================================
# Hardens and optimizes the Linux kernel by writing a complete
# set of sysctl overrides to /etc/sysctl.d/custom_overrides.conf
# and optionally disabling IPv6 at the GRUB boot level.
#
# Tunable parameters are read from configs/kernel.conf.
# All fixed security/performance values are hardcoded — they are
# not user-configurable because they have no sensible alternative
# for a production web server.
#
# Changes applied:
#   • Swap: vm.swappiness, vm.vfs_cache_pressure
#   • Network security: IP spoofing, SYN flood, source routing
#   • Network performance: port range, BBR, connection queues,
#                          socket buffers
#   • Filesystem: file-max, suid_dumpable
#   • IPv6: disable via GRUB kernel parameter (optional)
#   • Apport: disable crash reporter (optional)
#
# Reads from: configs/kernel.conf
# Writes to : /etc/sysctl.d/custom_overrides.conf
#             /etc/default/grub (if DISABLE_IPV6=yes)
# ================================================================

BASE_DIR="$(dirname "$(dirname "$(realpath "$0")")")"
CONFIG_FILE="$BASE_DIR/configs/kernel.conf"
LOG_FILE="$BASE_DIR/serverforge.log"

SYSCTL_FILE="/etc/sysctl.d/custom_overrides.conf"
GRUB_FILE="/etc/default/grub"

log() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') [KERNEL] $1" | tee -a "$LOG_FILE"
}

separator() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') [KERNEL] ────────────────────────────────" \
        | tee -a "$LOG_FILE"
}

# ── Pre-flight ────────────────────────────────────────────────────
if [ ! -f "$CONFIG_FILE" ]; then
    log "ERROR: Config not found at $CONFIG_FILE"
    exit 1
fi

source "$CONFIG_FILE"

separator
log "Starting kernel hardening..."
log "  SWAPPINESS        = $SWAPPINESS"
log "  VFS_CACHE_PRESSURE= $VFS_CACHE_PRESSURE"
log "  DISABLE_IPV6      = $DISABLE_IPV6"
log "  DISABLE_APPORT    = $DISABLE_APPORT"

# ── Step 1: Write sysctl overrides ───────────────────────────────
log "Step 1/4 — Writing kernel parameter overrides to $SYSCTL_FILE..."

# Backup existing file if present
if [ -f "$SYSCTL_FILE" ] && [ ! -f "${SYSCTL_FILE}.bak" ]; then
    cp "$SYSCTL_FILE" "${SYSCTL_FILE}.bak"
    log "Existing file backed up to ${SYSCTL_FILE}.bak"
fi

cat > "$SYSCTL_FILE" << EOF
# ================================================================
# ServerForge — Kernel Parameter Overrides
# Managed by: serverforge/scripts/kernel_hardening.sh
# Do not edit this file manually — re-run the script to update.
# ================================================================

# ── SWAP BEHAVIOUR ───────────────────────────────────────────────
# Use swap only as a last resort (0 = never swap, 100 = swap aggressively).
vm.swappiness = ${SWAPPINESS}

# Hold filesystem directory/inode cache in RAM longer.
# Lower value = kernel evicts cache less aggressively.
vm.vfs_cache_pressure = ${VFS_CACHE_PRESSURE}

# ── IP SPOOFING PROTECTION ────────────────────────────────────────
# Reverse path filtering: drop packets whose source address is not
# reachable via the interface they arrived on.
net.ipv4.conf.default.rp_filter = 1
net.ipv4.conf.all.rp_filter = 1

# ── SYN FLOOD PROTECTION ─────────────────────────────────────────
# Enable SYN cookies: encode connection state into the sequence number
# when the backlog is full — avoids allocating memory for half-open
# connections during a flood.
net.ipv4.tcp_syncookies = 1
# Increase the queue for half-open (SYN-received) connections.
net.ipv4.tcp_max_syn_backlog = 2048
# Reduce retries on stalled handshakes to free resources faster.
net.ipv4.tcp_synack_retries = 2
net.ipv4.tcp_syn_retries = 5

# ── SOURCE PACKET ROUTING ─────────────────────────────────────────
# Disable IP source routing — a legacy feature routinely abused in
# routing attacks. No legitimate traffic uses this today.
net.ipv4.conf.all.accept_source_route = 0
net.ipv6.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0
net.ipv6.conf.default.accept_source_route = 0

# ── TCP CONGESTION CONTROL — BBR ──────────────────────────────────
# BBR (Bottleneck Bandwidth and RTT) models the network path rather
# than reacting to packet loss. Delivers higher throughput and lower
# latency under load compared to the default cubic algorithm.
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr

# ── EPHEMERAL PORT RANGE ──────────────────────────────────────────
# Expand the range of ports available for outbound connections.
# Default is 32768–60999; this extends it to the full usable range.
net.ipv4.ip_local_port_range = 1024 65535

# ── FILE DESCRIPTORS AND CORE DUMPS ──────────────────────────────
# System-wide maximum open file descriptors. Critical for Nginx
# handling many simultaneous connections (each socket = 1 fd).
fs.file-max = 2097152
# Prevent setuid programs from generating core dumps that could
# leak sensitive memory content (passwords, keys) to disk.
fs.suid_dumpable = 0

# ── CONNECTION QUEUES ─────────────────────────────────────────────
# Maximum length of the listen backlog (completed connections
# waiting for accept()). Default of 4096 is easily exhausted.
net.core.somaxconn = 65535
# Queue size for packets arriving faster than the kernel can process.
net.core.netdev_max_backlog = 262144

# ── SOCKET MEMORY BUFFERS ─────────────────────────────────────────
# Larger buffers allow the kernel to handle more data per connection,
# improving throughput on high-bandwidth or high-latency paths.
net.core.optmem_max = 25165824
net.core.rmem_default = 31457280
net.core.rmem_max = 67108864
net.core.wmem_default = 31457280
net.core.wmem_max = 67108864
EOF

if [ $? -ne 0 ]; then
    log "ERROR: Failed to write $SYSCTL_FILE"
    exit 1
fi
log "$SYSCTL_FILE written successfully."

# ── Step 2: Apply sysctl parameters live ─────────────────────────
log "Step 2/4 — Applying kernel parameters (live, without reboot)..."
sysctl -p "$SYSCTL_FILE" >> "$LOG_FILE" 2>&1

if [ $? -ne 0 ]; then
    log "WARN: sysctl -p reported errors. Some parameters may require"
    log "      a reboot or a kernel that supports them. Check the log."
else
    log "Kernel parameters applied successfully."
fi

# ── Step 3: Disable IPv6 via GRUB ────────────────────────────────
if [ "$DISABLE_IPV6" = "yes" ]; then
    log "Step 3/4 — Disabling IPv6 via GRUB kernel parameter..."

    if [ ! -f "$GRUB_FILE" ]; then
        log "ERROR: $GRUB_FILE not found. Cannot disable IPv6."
        exit 1
    fi

    if [ ! -f "${GRUB_FILE}.bak" ]; then
        cp "$GRUB_FILE" "${GRUB_FILE}.bak"
        log "GRUB config backed up to ${GRUB_FILE}.bak"
    fi

    # Check the current GRUB_CMDLINE_LINUX value
    CURRENT_CMDLINE=$(grep '^GRUB_CMDLINE_LINUX=' "$GRUB_FILE" | sed 's/GRUB_CMDLINE_LINUX=//' | tr -d '"')

    if echo "$CURRENT_CMDLINE" | grep -q 'ipv6.disable'; then
        log "  ipv6.disable already present in GRUB_CMDLINE_LINUX — skipping."
    elif [ -z "$CURRENT_CMDLINE" ]; then
        # Empty string — replace the whole line safely
        sed -i 's|^GRUB_CMDLINE_LINUX=""$|GRUB_CMDLINE_LINUX="ipv6.disable=1"|' "$GRUB_FILE"
        log "  GRUB_CMDLINE_LINUX set to: ipv6.disable=1"
    else
        # Existing params present — append ipv6.disable=1
        sed -i "s|^GRUB_CMDLINE_LINUX=\"\(.*\)\"|GRUB_CMDLINE_LINUX=\"\1 ipv6.disable=1\"|" "$GRUB_FILE"
        log "  Appended ipv6.disable=1 to existing GRUB_CMDLINE_LINUX."
    fi

    log "  Regenerating GRUB boot configuration..."
    update-grub >> "$LOG_FILE" 2>&1

    if [ $? -ne 0 ]; then
        log "ERROR: update-grub failed. Restoring GRUB backup."
        cp "${GRUB_FILE}.bak" "$GRUB_FILE"
        exit 1
    fi
    log "  GRUB updated. IPv6 will be disabled at next boot."
else
    log "Step 3/4 — IPv6 disable skipped (DISABLE_IPV6=$DISABLE_IPV6)."
fi

# ── Step 4: Disable apport crash reporter ────────────────────────
if [ "$DISABLE_APPORT" = "yes" ]; then
    log "Step 4/4 — Disabling apport crash reporter..."

    if systemctl is-enabled apport &>/dev/null; then
        systemctl disable apport >> "$LOG_FILE" 2>&1
        systemctl stop apport >> "$LOG_FILE" 2>&1
        log "  Apport disabled and stopped."
    else
        log "  Apport is already disabled or not present."
    fi
else
    log "Step 4/4 — Apport disable skipped (DISABLE_APPORT=$DISABLE_APPORT)."
fi

# ── Summary ───────────────────────────────────────────────────────
separator
log "Kernel hardening complete."
log "  ✔ sysctl overrides → $SYSCTL_FILE"
log "  ✔ vm.swappiness    → $SWAPPINESS"
log "  ✔ BBR congestion   → enabled"
log "  ✔ IP spoofing      → blocked (rp_filter=1)"
log "  ✔ SYN flood        → protected (syncookies=1)"
log "  ✔ IPv6             → $DISABLE_IPV6 (takes effect after reboot via GRUB)"
log "  ✔ Apport           → disabled: $DISABLE_APPORT"
log "  A reboot is needed to confirm all changes survive the full boot sequence."
